export const LOADING_CONTACT="LOADING_CONTACT";
export const GET_ALL_CONTACT_SUCCESS = "GET_ALL_CONTACT_SUCCESS";
export const GET_ALL_CONTACT_FAIL = "GET_ALL_CONTACT_FAIL";


export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";
export const ADD_CONTACT_FAIL = "ADD_CONTACT_FAIL";


export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_FAIL = "DELETE_CONTACT_FAIL";

export const GET_ONE_CONTACT_SUCCESS = "GET_ONE_CONTACT_SUCCESS";
export const GET_ONE_CONTACT_FAIL = "GET_ONE_CONTACT_FAIL";

export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";
export const UPDATE_CONTACT_FAIL = "UPDATE_CONTACT_FAIL";