export const LOADING_COURSES="LOADING_COURSES";
export const GET_ALL_COURSES_SUCCESS = "GET_ALL_COURSES_SUCCESS";
export const GET_ALL_COURSES_FAIL = "GET_ALL_COURSES_FAIL";


export const ADD_COURSES_SUCCESS = "ADD_COURSES_SUCCESS";
export const ADD_COURSES_FAIL = "ADD_COURSES_FAIL";


export const DELETE_COURSES_SUCCESS = "DELETE_COURSES_SUCCESS";
export const DELETE_COURSES_FAIL = "DELETE_COURSES_FAIL";

export const GET_ONE_COURSES_SUCCESS = "GET_ONE_COURSES_SUCCESS";
export const GET_ONE_COURSES_FAIL = "GET_ONE_COURSES_FAIL";

export const UPDATE_COURSES_SUCCESS = "UPDATE_COURSES_SUCCESS";
export const UPDATE_COURSES_FAIL = "UPDATE_COURSES_FAIL";