export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOADING_USERS = "LOADING_USERS";

export const GET_CANDIDAT_SUCCESS = " GET_CANDIDAT_SUCCESS";
export const GET_CANDIDAT_FAIL = " GET_CANDIDAT_FAIL";

export const DELETE_CANDIDAT_SUCCESS = " DELETE_CANDIDAT_SUCCESS";
export const DELETE_CANDIDAT_FAIL = " DELETE_CANDIDAT_FAIL";

export const GET_FORMATEUR_SUCCESS = " GET_FORMATEUR_SUCCESS";
export const GET_FORMATEUR_FAIL = " GET_FORMATEUR_FAIL";

export const DELETE_FORMATEUR_SUCCESS = " DELETE_FORMATEUR_SUCCESS";
export const DELETE_FORMATEUR_FAIL = " DELETE_FORMATEUR_FAIL";

export const LOGOUT = "LOGOUT";